import { SUPABASE_URL, SUPABASE_ANON_KEY, getSession, signIn, signUp, onAuthChange, saveQuestionnaire, fetchSubmissionById, submitClientQuestionnaire } from './supabase.js';
import { initLayout } from './nav.js';

const REQ_API_URL = `${SUPABASE_URL}/functions/v1/generate-requirements`;

/* ---------- DOM helpers ---------- */
const $ = (id) => document.getElementById(id);
const esc = (s) => String(s == null ? '' : s)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const list = (items) => items && items.length
  ? `<ul class="p-list">${items.map((i) => `<li>${esc(i)}</li>`).join('')}</ul>` : '';
const sectionHead = (n, title) =>
  `<div class="p-section__head"><span class="p-section__num">${esc(String(n))}</span><h2 class="p-section__title">${esc(title)}</h2></div>`;
const subHead = (major, minor, title) =>
  `<div class="p-subhead"><span class="p-subhead__num">${esc(String(major))}.${esc(String(minor))}</span><span class="p-subhead__title">${esc(title)}</span></div>`;
const terms = (items, keyField, valField) => items && items.length
  ? items.map((i) => `<p class="p-term"><span class="p-term__h">${esc(i[keyField])}:</span> ${esc(i[valField])}</p>`).join('')
  : '';

/* Static SRD boilerplate (not generated by the LLM, to keep it accurate and consistent) */
const SRD_REFERENCES = [
  'IEEE Std 830-1998 — IEEE Recommended Practice for Software Requirements Specifications',
  'PocketDevs Internal Engineering & Documentation Standards',
  'Client intake questionnaire responses (primary source for this document)',
];
const SRD_OVERVIEW = 'The remainder of this document is organized as follows: Section 2 provides an overall description of the product, its users, and its operating environment. Section 3 specifies the functional requirements grouped by feature module. Section 4 covers external interface requirements. Section 5 specifies non-functional requirements covering performance, security, and other quality attributes. Section 6 covers data, legal/compliance, and acceptance criteria considerations. Appendix A defines the requirement priority legend used throughout this document, and Appendix B tracks the document\'s revision history.';

/* ---------- Questions & Steps ---------- */
const Q = {
  // Contact
  contactName:    { label: 'Your full name', type: 'text', required: true, placeholder: 'e.g. Juan dela Cruz' },
  contactCompany: { label: 'Company or organization name', type: 'text', placeholder: 'e.g. Acme Trading Corp' },
  contactEmail:   { label: 'Your email address', type: 'email', placeholder: 'you@company.com' },
  contactIndustry: {
    label: 'What industry are you in?', type: 'text', placeholder: 'e.g. Retail, Healthcare, Logistics, Food & Beverage',
    help: 'This helps us understand your business context and recommend the right solutions.',
  },

  // Project
  projectType: {
    label: 'What type of digital product do you need built?', type: 'radio', required: true,
    options: [
      { value: 'website',  label: 'Website',              hint: 'Company profile, e-commerce store, portfolio, landing page, or blog' },
      { value: 'webapp',   label: 'Web Application',      hint: 'A browser-based tool with user accounts — think dashboards, booking systems, online platforms' },
      { value: 'mobile',   label: 'Mobile App',           hint: 'An app your customers download on their iPhone or Android phone' },
      { value: 'software', label: 'Custom Software',      hint: 'Internal business tool, desktop program, automation, POS system, or back-end system' },
    ],
  },
  projectName:        { label: 'Project name or working title', type: 'text', placeholder: 'e.g. ShopMate, EcoTrack, Acme POS (can be anything for now)' },
  projectDescription: {
    label: 'Describe your project in 2–3 sentences', type: 'textarea', required: true,
    placeholder: 'e.g. An online store where customers can browse our clothing catalog, place orders, and pay via GCash or credit card.',
    help: 'Just describe it in plain words — no technical jargon needed.',
  },
  projectProblem: {
    label: 'What problem does this solve for you or your customers?', type: 'textarea',
    placeholder: 'e.g. Right now we handle orders manually through Facebook Messenger which causes delays and missed orders.',
    help: 'Understanding the "why" helps us build something that truly fixes the issue, not just a generic solution.',
  },

  // Website
  websiteType: {
    label: 'What kind of website is this?', type: 'radio',
    options: [
      { value: 'company',   label: 'Company / Business profile', hint: 'Showcases who you are, your services, and lets people contact you' },
      { value: 'ecommerce', label: 'Online store',               hint: 'Customers can browse products, add to cart, and pay online' },
      { value: 'portfolio', label: 'Portfolio / Showcase',       hint: 'Displays your work, projects, or creative output' },
      { value: 'blog',      label: 'Blog / News site',           hint: 'Regularly updated articles, announcements, or media content' },
      { value: 'landing',   label: 'Landing / Marketing page',   hint: 'Single page to promote a product or collect leads' },
      { value: 'other',     label: 'Something else',             hint: 'Describe it in the project description field' },
    ],
  },
  websitePages: {
    label: 'Roughly how many pages do you need?', type: 'text', placeholder: 'e.g. 6 pages (Home, About, Services, Team, Blog, Contact)',
    help: 'More pages generally means more time and cost. Common pages: Home, About, Services/Products, Portfolio, Contact.',
  },
  websiteCMS: {
    label: 'Do you want to update the website content yourself?', type: 'radio',
    help: 'A CMS (Content Management System) is like a control panel for your website — it lets your team add blog posts, update prices, or change photos without needing a developer each time. Think of it like editing a Google Doc for your website.',
    options: [
      { value: 'yes',    label: 'Yes — we\'ll update it regularly',        hint: 'Blog posts, products, team members, etc.' },
      { value: 'no',     label: 'No — content stays mostly the same',      hint: 'We\'ll update it for you when needed' },
      { value: 'unsure', label: 'Not sure yet' },
    ],
  },
  websiteDesign: {
    label: 'Do you have a brand identity ready?', type: 'radio',
    help: 'Brand identity includes your logo, colors (e.g. blue and white), and fonts. If you already have these, we can match the website to your existing look.',
    options: [
      { value: 'yes',     label: 'Yes — logo, colors, and fonts are ready' },
      { value: 'partial', label: 'Partial — I have a logo but nothing else' },
      { value: 'no',      label: 'No — I need a complete brand and design' },
    ],
  },
  websiteFeatures: {
    label: 'Which features do you need on the website? (select all that apply)', type: 'checkboxes',
    help: 'Don\'t worry if you\'re unsure about some — just pick what sounds relevant. We\'ll confirm everything during our call.',
    options: ['Contact Form', 'Image / Product Gallery', 'Customer Testimonials', 'Newsletter Signup (email list)', 'Blog / Articles section', 'Online Booking / Scheduling', 'Live Chat', 'Social Media Feed', 'Google Maps / Location', 'Multiple languages', 'Video section', 'Customer login / Member portal', 'Product catalog', 'Online payments / Checkout'],
  },
  websiteIntegrations: {
    label: 'Any tools or platforms to connect with the website?', type: 'textarea',
    placeholder: 'e.g. Facebook Pixel, Google Analytics, Lazada/Shopee feed, GCash/PayMongo, Mailchimp, WhatsApp button',
    help: 'Integrations connect your website to other tools you already use. If unsure, just list the tools your business uses and we\'ll figure it out.',
  },

  // Web App
  webappFeatures: {
    label: 'List the main things users should be able to do in this app', type: 'textarea', required: true,
    placeholder: 'e.g.\n- Customers can register and create a profile\n- Browse and filter a product catalog\n- Place and track orders\n- Admin can view all orders and update status\n- Generate sales reports',
    help: 'Think of every action a user can take — from signing up to completing their main task. List as many as you can; we\'ll organize them for you.',
  },
  webappAuth: {
    label: 'Do users need to create an account and log in?', type: 'radio',
    help: 'Authentication (login) lets you know who each user is. This is needed if different users should see different data, or if there\'s sensitive information to protect.',
    options: [
      { value: 'yes',    label: 'Yes — users have their own accounts',   hint: 'Customers, members, or users each log in to their own space' },
      { value: 'public', label: 'No — anyone can use it without logging in', hint: 'Like a public directory or read-only dashboard' },
      { value: 'admin',  label: 'Only staff/admins log in',              hint: 'It\'s an internal tool — customers don\'t need accounts' },
    ],
  },
  webappRoles: {
    label: 'What user roles or permission levels do you need?', type: 'text',
    placeholder: 'e.g. Super Admin, Store Manager, Cashier, Customer',
    help: 'Roles control what each type of user can see or do. Example: a Cashier can process sales but can\'t delete records; a Manager can view reports.',
  },
  webappAdmin: {
    label: 'Do you need an admin dashboard to manage the system?', type: 'radio',
    help: 'An admin dashboard is a private area where you or your team can manage users, view data, run reports, and control settings — like a back-office for the system.',
    options: [
      { value: 'yes',    label: 'Yes — we need a full admin area' },
      { value: 'no',     label: 'No — just the main user-facing app' },
      { value: 'unsure', label: 'Not sure yet' },
    ],
  },
  webappPayments: {
    label: 'Will users need to pay online?', type: 'radio',
    help: 'Payment integration connects the app to payment services like GCash, PayMongo, Maya, or credit cards so users can pay directly without leaving the app.',
    options: [
      { value: 'yes',    label: 'Yes — online payments are needed',        hint: 'GCash, Maya, credit/debit card, bank transfer' },
      { value: 'no',     label: 'No — no payment processing needed' },
      { value: 'future', label: 'Not now, but we might add it later' },
    ],
  },
  webappRealtime: {
    label: 'Do you need any real-time features? (select all that apply)', type: 'checkboxes',
    help: 'Real-time features update automatically without refreshing the page. Example: a customer sees their order status change live, or a chat message appears instantly.',
    options: ['Live notifications (e.g. new order alert)', 'Real-time chat / messaging', 'Live dashboard / data that auto-updates', 'Video or voice calls', 'None of the above'],
  },
  webappIntegrations: {
    label: 'Does this app need to connect with other services?', type: 'textarea',
    placeholder: 'e.g. PayMongo for payments, SendGrid for emails, Twilio for SMS, Google Maps, government APIs, existing POS system',
    help: 'Integrations are connections to outside tools and services. If you send emails, SMS, or accept payments, those are integrations.',
  },
  webappData: {
    label: 'Do you have existing data that needs to be imported?', type: 'radio',
    help: 'If you currently use spreadsheets, another software, or a manual system with existing records (customers, inventory, etc.), we may need to transfer that data into the new system.',
    options: [
      { value: 'yes', label: 'Yes — we have data to migrate (spreadsheets, old system, etc.)' },
      { value: 'no',  label: 'No — we\'re starting fresh with no existing data' },
    ],
  },

  // Mobile
  mobilePlatform: {
    label: 'Which phones should the app work on?', type: 'radio',
    options: [
      { value: 'ios',     label: 'iPhone / iPad only (iOS)' },
      { value: 'android', label: 'Android only' },
      { value: 'both',    label: 'Both iPhone and Android', hint: 'Recommended for maximum reach' },
    ],
  },
  mobileTech: {
    label: 'Technology preference?', type: 'radio',
    help: 'Don\'t worry about the technical details — here\'s a simple explanation: Cross-platform means we build one codebase that works on both iPhone and Android (more cost-effective). Native means we build two separate apps, one for each platform (maximum performance but higher cost).',
    options: [
      { value: 'crossplatform', label: 'Cross-platform (React Native / Flutter)', hint: 'One codebase for both iOS and Android — more affordable, faster to build' },
      { value: 'native',        label: 'Native (Swift for iOS, Kotlin for Android)', hint: 'Built separately for each platform — best performance, higher cost' },
      { value: 'nopref',        label: 'No preference — recommend what\'s best', hint: 'We\'ll advise based on your budget and needs' },
    ],
  },
  mobileCategory: {
    label: 'What category best describes this app?', type: 'select',
    options: ['Productivity / Business tool', 'Shopping / E-commerce', 'Social / Community', 'Finance / Banking / Payments', 'Health / Fitness / Wellness', 'Food / Restaurant / Delivery', 'Education / E-learning', 'Entertainment / Media', 'Travel / Hospitality', 'Real Estate', 'Logistics / Delivery / Tracking', 'Other'],
  },
  mobileFeatures: {
    label: 'What are the main things a user can do in the app?', type: 'textarea', required: true,
    placeholder: 'e.g.\n- Browse and search products\n- Add to cart and check out with GCash\n- Track order status\n- View order history\n- Contact support via chat',
    help: 'Describe it like you\'re explaining the app to a friend. What would you tap on first? Then what?',
  },
  mobileSpecial: {
    label: 'Does the app need any special phone features? (select all that apply)', type: 'checkboxes',
    help: 'Modern phones have built-in features (camera, GPS, etc.) that apps can use. Select only what your app genuinely needs.',
    options: ['Push Notifications (alerts even when app is closed)', 'GPS / Maps (show location or give directions)', 'Camera (take photos or scan)', 'Works offline (no internet needed for some features)', 'In-App Purchases or subscriptions', 'QR Code Scanner', 'Face ID / Fingerprint login', 'Bluetooth / NFC', 'None of the above'],
  },
  mobileAppStore: {
    label: 'Do you need help publishing to the App Store / Play Store?', type: 'radio',
    help: 'Before users can download your app, it needs to be reviewed and approved by Apple (App Store) and Google (Play Store). This process can take 1–4 weeks and requires developer accounts.',
    options: [
      { value: 'yes',    label: 'Yes — handle the submission for us' },
      { value: 'no',     label: 'No — our team will handle the publishing' },
      { value: 'unsure', label: 'Not sure yet' },
    ],
  },

  // Custom Software
  softwareType: {
    label: 'What kind of software or system do you need?', type: 'select',
    help: 'Custom software is any system built specifically for your business\'s unique processes — not an off-the-shelf product.',
    options: ['Desktop Application (runs on a computer, not a browser)', 'Backend API / Service (powers other apps or integrations)', 'Data Processing / Reporting pipeline', 'Business Automation (replaces manual repetitive tasks)', 'Internal Business Tool / ERP (inventory, HR, operations)', 'Point of Sale (POS) System', 'Other'],
  },
  softwareEnvironment: {
    label: 'Where will this software run?', type: 'checkboxes',
    options: ['Windows computers', 'Mac computers', 'Linux servers', 'Cloud / Internet server', 'Inside a web browser (web-based)', 'Other'],
  },
  softwareUsers: {
    label: 'How many people will use this system?', type: 'text', placeholder: 'e.g. 5 employees, 2 branches, 500 customers per day',
    help: 'This helps us size the system correctly. Even a rough estimate is fine.',
  },
  softwarePerformance: {
    label: 'Any speed or capacity requirements?', type: 'textarea',
    placeholder: 'e.g. Must process 500 transactions per day; reports should generate in under 5 seconds; must support 10 users simultaneously',
    help: 'Performance requirements help us choose the right architecture. If you\'re unsure, just describe the busiest scenario you can imagine.',
  },
  softwareSecurity: {
    label: 'Security or compliance requirements?', type: 'checkboxes',
    help: 'Some industries have legal requirements for how data is stored and protected. If your business handles medical records, financial data, or personal information of EU citizens, there may be specific rules to follow.',
    options: ['Standard security (password protection, encrypted data)', 'GDPR (you handle data of people in Europe)', 'HIPAA (you handle medical / health records)', 'PCI-DSS (you process credit/debit card payments)', 'None of the above / Unsure'],
  },
  softwareIntegrations: {
    label: 'Does this system need to connect with other tools or platforms?', type: 'textarea',
    placeholder: 'e.g. QuickBooks for accounting, our existing POS, government BIR eFPS, SMS provider, email service',
    help: 'Integrations allow the new system to exchange data with tools your business already uses.',
  },

  // Users & Audience
  targetUsers: {
    label: 'Who are the people who will use this?', type: 'textarea', required: true,
    placeholder: 'e.g. Small business owners in the Philippines aged 25–45 who currently manage their inventory in spreadsheets and want something simpler.',
    help: 'The more specific you are, the better we can design for them. Think: who is the typical user, what do they know, and what\'s their main goal?',
  },
  userCount: {
    label: 'How many users do you expect?', type: 'select',
    help: 'This is just an estimate — it helps us design the right infrastructure. A system for 50 internal staff needs different planning than one for 50,000 customers.',
    options: ['Under 100 (small team or pilot)', '100 – 1,000', '1,000 – 10,000', '10,000 – 100,000', 'Over 100,000', 'Not sure yet'],
  },
  devices: {
    label: 'What devices will your users mainly use?', type: 'checkboxes',
    help: 'This determines how much effort goes into mobile design. If most of your users are on phones, we\'ll prioritize a mobile-friendly layout.',
    options: ['Desktop or laptop computer', 'Mobile phone', 'Tablet', 'Mix of all the above'],
  },

  // Timeline & Budget
  targetDate: {
    label: 'When do you need this ready?', type: 'text', placeholder: 'e.g. December 2026, within 3 months, before the holiday season',
    help: 'A rough timeframe is fine. If there\'s a specific event or deadline driving this (e.g. a product launch, a trade show), mention it.',
  },
  flexibleTimeline: {
    label: 'Is this deadline firm?', type: 'radio',
    options: [
      { value: 'yes',    label: 'Yes — somewhat flexible',    hint: 'Preferred date but can adjust' },
      { value: 'no',     label: 'No — hard deadline',          hint: 'There\'s a specific event or contract date' },
      { value: 'unsure', label: 'No specific deadline yet' },
    ],
  },
  budgetRange: {
    label: 'What\'s your approximate budget? (in Philippine Pesos)', type: 'radio',
    help: 'We understand this can be a sensitive question. Sharing a range helps us recommend the right scope and approach so we don\'t waste each other\'s time. All information is confidential.',
    options: [
      { value: 'under50k',  label: 'Under ₱50,000',               hint: 'Best for simple landing pages or very limited features' },
      { value: '50k-150k',  label: '₱50,000 – ₱150,000',          hint: 'Suitable for small websites or basic apps' },
      { value: '150k-300k', label: '₱150,000 – ₱300,000',         hint: 'Covers most mid-range websites and apps' },
      { value: '300k-500k', label: '₱300,000 – ₱500,000',         hint: 'For complex web apps with multiple features' },
      { value: '500k-1m',   label: '₱500,000 – ₱1,000,000',       hint: 'Large-scale platforms and enterprise systems' },
      { value: 'over1m',    label: 'Over ₱1,000,000',              hint: 'Enterprise-grade systems or full product development' },
      { value: 'discuss',   label: 'Prefer to discuss in the call', hint: 'That\'s fine — we\'ll figure it out together' },
    ],
  },
  hasExisting: {
    label: 'Do you currently have an existing website or system?', type: 'radio',
    options: [
      { value: 'current',  label: 'Yes — and it\'s working fine',           hint: 'We\'re enhancing or replacing it' },
      { value: 'outdated', label: 'Yes — but it\'s outdated or broken',     hint: 'Needs a refresh or full rebuild' },
      { value: 'none',     label: 'No — we\'re starting from zero' },
    ],
  },

  // Additional
  references: {
    label: 'Any websites or apps that inspire you?', type: 'textarea',
    placeholder: 'e.g. I like how Grab has a simple tracking screen. The dashboard on Shopify is clean. Lazada\'s product page is a good reference.',
    help: 'You don\'t need links — just describe what you like about them. This helps us understand your taste and expectations.',
  },
  techPreferences: {
    label: 'Any technical preferences or constraints?', type: 'textarea',
    placeholder: 'e.g. Must be hosted locally in the Philippines, must work with our existing Microsoft 365 setup, prefer open-source tools',
    help: 'Leave blank if you have no specific requirements. We\'ll choose the best technology stack for your needs.',
  },
  mustHave: {
    label: 'What\'s the single most important thing this project must nail?', type: 'textarea',
    placeholder: 'e.g. It must be so simple that my 60-year-old staff can use it without training.',
    help: 'If we can only get one thing absolutely right, what would it be? This becomes our North Star when making design decisions.',
  },
  additionalNotes: {
    label: 'Anything else you\'d like to share?', type: 'textarea',
    placeholder: 'Any context, concerns, past experiences with developers, or things you want us to be aware of.',
    help: 'This is your space to add anything that didn\'t fit the previous questions.',
  },
};

const STEPS = [
  { id: 'contact',  title: 'About You',         questions: ['contactName', 'contactCompany', 'contactEmail', 'contactIndustry'] },
  { id: 'project',  title: 'Your Project',       questions: ['projectType', 'projectName', 'projectDescription', 'projectProblem'] },
  { id: 'website',  title: 'Website Details',    questions: ['websiteType', 'websitePages', 'websiteCMS', 'websiteDesign', 'websiteFeatures', 'websiteIntegrations'], when: (a) => a.projectType === 'website' },
  { id: 'webapp',   title: 'Web App Details',    questions: ['webappFeatures', 'webappAuth', 'webappRoles', 'webappAdmin', 'webappPayments', 'webappRealtime', 'webappIntegrations', 'webappData'], when: (a) => a.projectType === 'webapp' },
  { id: 'mobile',   title: 'Mobile App Details', questions: ['mobilePlatform', 'mobileTech', 'mobileCategory', 'mobileFeatures', 'mobileSpecial', 'mobileAppStore'], when: (a) => a.projectType === 'mobile' },
  { id: 'software', title: 'Software Details',   questions: ['softwareType', 'softwareEnvironment', 'softwareUsers', 'softwarePerformance', 'softwareSecurity', 'softwareIntegrations'], when: (a) => a.projectType === 'software' },
  { id: 'users',    title: 'Users & Audience',   questions: ['targetUsers', 'userCount', 'devices'] },
  { id: 'timeline', title: 'Timeline & Budget',  questions: ['targetDate', 'flexibleTimeline', 'budgetRange', 'hasExisting'] },
  { id: 'extra',    title: 'Additional Info',     questions: ['references', 'techPreferences', 'mustHave', 'additionalNotes'] },
];

/* ---------- State ---------- */
let answers = {};
let currentQuestionIndex = 0;
let isShareMode = false;
let currentSubmissionId = null;
let clientInviteOwnerId = null;
// undefined = not resolved yet, null = confirmed logged out, object = logged in.
// Always updated via updateAuthState()/onAuthChange — never re-fetched with a
// fresh getSession() call at click-time, since that races with the Supabase
// client's session-recovery-from-storage on a freshly loaded page.
let currentSession;

function getActiveSteps() {
  return STEPS.filter((s) => !s.when || s.when(answers));
}

/* Flatten the active steps into a single ordered list of questions, so the
   wizard can present one question per screen (Typeform-style). */
function getActiveQuestions() {
  const out = [];
  getActiveSteps().forEach((step) => {
    step.questions.forEach((qid) => out.push({ qid, stepId: step.id, stepTitle: step.title }));
  });
  return out;
}

/* ---------- Render one question (Typeform-style) ---------- */
function renderField(qid, value) {
  const q = Q[qid];
  if (!q) return '';
  const val = value != null ? value : '';
  const id = `rq_${qid}`;

  if (q.type === 'text' || q.type === 'email') {
    return `<input id="${id}" name="${qid}" class="tf-input" type="${q.type}" placeholder="${esc(q.placeholder || 'Type your answer here…')}" value="${esc(val)}" autocomplete="off" />`;
  }

  if (q.type === 'textarea') {
    return `<textarea id="${id}" name="${qid}" class="tf-input tf-input--area" rows="3" placeholder="${esc(q.placeholder || 'Type your answer here…')}">${esc(val)}</textarea>`;
  }

  if (q.type === 'radio' || q.type === 'select') {
    const opts = q.type === 'select'
      ? q.options.map((o) => ({ value: o, label: o }))
      : q.options.map((o) => ({ value: o.value, label: o.label, hint: o.hint }));
    const cards = opts.map((o, i) => {
      const sel = val === o.value;
      return `<button type="button" class="tf-choice ${sel ? 'tf-choice--selected' : ''}" data-value="${esc(o.value)}" data-qid="${qid}">
        <span class="tf-choice__key">${String.fromCharCode(65 + i)}</span>
        <span class="tf-choice__main"><span class="tf-choice__label">${esc(o.label)}</span>${o.hint ? `<span class="tf-choice__hint">${esc(o.hint)}</span>` : ''}</span>
        <span class="tf-choice__tick" aria-hidden="true">✓</span>
      </button>`;
    }).join('');
    return `<div class="tf-choices" data-qid="${qid}" data-multi="false">${cards}</div>`;
  }

  if (q.type === 'checkboxes') {
    const checked = Array.isArray(val) ? val : [];
    const cards = q.options.map((o, i) => {
      const sel = checked.includes(o);
      return `<button type="button" class="tf-choice ${sel ? 'tf-choice--selected' : ''}" data-value="${esc(o)}" data-qid="${qid}">
        <span class="tf-choice__key">${String.fromCharCode(65 + i)}</span>
        <span class="tf-choice__main"><span class="tf-choice__label">${esc(o)}</span></span>
        <span class="tf-choice__tick" aria-hidden="true">✓</span>
      </button>`;
    }).join('');
    return `<div class="tf-choices tf-choices--multi" data-qid="${qid}" data-multi="true">${cards}</div>`;
  }

  return '';
}

function renderCurrentQuestion() {
  const active = getActiveQuestions();
  if (!active.length) return;
  if (currentQuestionIndex < 0) currentQuestionIndex = 0;
  if (currentQuestionIndex > active.length - 1) currentQuestionIndex = active.length - 1;

  const item = active[currentQuestionIndex];
  const q = Q[item.qid];
  const num = currentQuestionIndex + 1;
  const isLast = currentQuestionIndex === active.length - 1;
  const isMulti = q.type === 'checkboxes';
  const helpHtml = q.help ? `<p class="tf-q__help">${q.help.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')}</p>` : '';

  $('rqStepCard').innerHTML = `
    <div class="tf-q" data-qid="${item.qid}">
      <div class="tf-q__num">${num} <span class="tf-q__arrow">→</span></div>
      <div class="tf-q__head">
        <h2 class="tf-q__title">${esc(q.label)}${q.required ? '<span class="tf-q__req">*</span>' : ''}</h2>
        ${helpHtml}
      </div>
      <div class="tf-q__field">${renderField(item.qid, answers[item.qid])}</div>
      <div class="tf-q__actions">
        <button type="button" class="tf-ok" id="rqOkBtn">${isLast ? 'Review' : 'OK'} <span class="tf-ok__check">✓</span></button>
        <span class="tf-q__keyhint">${isMulti ? 'select all that apply, then press <b>Enter ↵</b>' : 'press <b>Enter ↵</b>'}</span>
      </div>
    </div>
  `;

  $('rqProgressBar').style.width = `${(currentQuestionIndex / active.length) * 100}%`;
  $('rqStepLabel').textContent = `${num} of ${active.length}`;
  $('rqBackBtn').disabled = currentQuestionIndex === 0;

  wireQuestionInteractions(item.qid);

  // Focus the text field for typed questions
  const input = $('rqStepCard').querySelector('.tf-input');
  if (input) setTimeout(() => input.focus(), 60);
}

function wireQuestionInteractions(qid) {
  const card = $('rqStepCard');
  const ok = $('rqOkBtn');
  if (ok) ok.addEventListener('click', goNext);

  const wrap = card.querySelector('.tf-choices');
  if (wrap) {
    const multi = wrap.dataset.multi === 'true';
    wrap.querySelectorAll('.tf-choice').forEach((btn) => {
      btn.addEventListener('click', () => selectChoice(btn, multi));
    });
  }
}

function selectChoice(btn, multi) {
  const wrap = btn.closest('.tf-choices');
  if (!wrap) return;
  if (multi) {
    btn.classList.toggle('tf-choice--selected');
    collectCurrentAnswer();
  } else {
    wrap.querySelectorAll('.tf-choice').forEach((b) => b.classList.remove('tf-choice--selected'));
    btn.classList.add('tf-choice--selected');
    collectCurrentAnswer();
    clearStepError();
    // Auto-advance after a brief highlight (Typeform behaviour)
    setTimeout(() => goNext(), 280);
  }
}

/* ---------- Collect answers ---------- */
function collectCurrentAnswer() {
  const item = getActiveQuestions()[currentQuestionIndex];
  if (!item) return;
  const qid = item.qid;
  const q = Q[qid];
  if (q.type === 'checkboxes') {
    const selected = $('rqStepCard').querySelectorAll(`.tf-choice--selected[data-qid="${qid}"]`);
    answers[qid] = Array.from(selected).map((el) => el.dataset.value);
  } else if (q.type === 'radio' || q.type === 'select') {
    const sel = $('rqStepCard').querySelector(`.tf-choice--selected[data-qid="${qid}"]`);
    answers[qid] = sel ? sel.dataset.value : (answers[qid] || '');
  } else {
    const el = $(`rq_${qid}`);
    if (el) answers[qid] = el.value.trim();
  }
}

function validateCurrentQuestion() {
  const item = getActiveQuestions()[currentQuestionIndex];
  if (!item) return true;
  const q = Q[item.qid];
  if (!q.required) return true;
  const val = answers[item.qid];
  if (!val || (Array.isArray(val) && !val.length)) {
    showStepError('This field is required to continue.');
    return false;
  }
  return true;
}

function showStepError(msg) {
  let el = $('rqStepError');
  if (!el) {
    el = document.createElement('div');
    el.id = 'rqStepError';
    el.className = 'tf-error';
  }
  const field = $('rqStepCard').querySelector('.tf-q__field');
  const actions = $('rqStepCard').querySelector('.tf-q__actions');
  if (field && actions && el.parentNode !== field.parentNode) {
    field.parentNode.insertBefore(el, actions);
  }
  el.textContent = msg;
  el.hidden = false;
}

function clearStepError() {
  const el = $('rqStepError');
  if (el) el.hidden = true;
}

/* ---------- Navigation ---------- */
function goNext() {
  collectCurrentAnswer();
  if (!validateCurrentQuestion()) return;
  clearStepError();
  const active = getActiveQuestions();
  if (currentQuestionIndex < active.length - 1) {
    currentQuestionIndex++;
    renderCurrentQuestion();
    window.scrollTo({ top: 0, behavior: 'smooth' });
  } else {
    showReview();
  }
}

function goBack() {
  clearStepError();
  if (currentQuestionIndex > 0) {
    currentQuestionIndex--;
    renderCurrentQuestion();
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }
}

/* ---------- Review screen ---------- */
function showReview() {
  collectCurrentAnswer();
  $('rqWizard').hidden = true;
  $('rqReview').hidden = false;

  renderAnswersSummary();

  if (clientInviteOwnerId) {
    // A client filling via an invite link — they submit straight to the owner.
    $('rqSharePanel').hidden = true;
    $('rqStaffPanel').hidden = true;
    $('rqSubmitPanel').hidden = false;
    $('rqReviewTitle').textContent = 'Review your answers';
    $('rqReviewSub').textContent = 'Take a quick look — you can edit anything before sending it to PocketDevs.';
  } else if (isShareMode) {
    $('rqSharePanel').hidden = true;
    $('rqStaffPanel').hidden = false;
    $('rqReviewTitle').textContent = 'Client requirements summary';
    $('rqReviewSub').textContent = 'Review the client\'s answers below. You can edit any field, then generate the SRD.';
  } else {
    $('rqShareUrl').value = buildShareUrl();
  }
}

function renderAnswersSummary() {
  const STEP_LABELS = {
    contact:  'About the Client',
    project:  'Project Overview',
    website:  'Website Details',
    webapp:   'Web App Details',
    mobile:   'Mobile App Details',
    software: 'Software Details',
    users:    'Users & Audience',
    timeline: 'Timeline & Budget',
    extra:    'Additional Info',
  };
  const activeSteps = getActiveSteps();
  const html = activeSteps.map((step) => {
    const rows = step.questions.map((qid) => {
      const q = Q[qid];
      const val = answers[qid];
      if (!val || (Array.isArray(val) && !val.length)) return '';
      const display = Array.isArray(val) ? val.join(', ') : val;
      const labelMap = {};
      if (q.type === 'radio' && Array.isArray(q.options)) {
        q.options.forEach((o) => { if (o.value) labelMap[o.value] = o.label; });
      }
      const displayVal = labelMap[display] || display;
      return `<div class="rq-summary__row">
        <div class="rq-summary__label">${esc(q.label)}</div>
        <div class="rq-summary__value">${esc(displayVal)}</div>
      </div>`;
    }).filter(Boolean).join('');
    if (!rows) return '';
    return `<div class="card rq-summary__section">
      <h3 class="rq-summary__heading">${esc(STEP_LABELS[step.id] || step.title)}</h3>
      ${rows}
    </div>`;
  }).join('');
  $('rqAnswersSummary').innerHTML = html;
}

function showWizard() {
  $('rqReview').hidden = true;
  $('rqWizard').hidden = false;
  renderCurrentQuestion();
  window.scrollTo({ top: 0, behavior: 'smooth' });
}

/* ---------- Client submit (via invite link) ---------- */
async function submitClientAnswers() {
  const btn = $('rqSubmitBtn');
  const statusEl = $('rqSubmitStatus');
  btn.disabled = true;
  statusEl.className = 'status status--working';
  statusEl.innerHTML = '<span class="spinner"></span> Sending your answers…';
  statusEl.hidden = false;
  try {
    const { ok, error } = await submitClientQuestionnaire(clientInviteOwnerId, answers);
    if (!ok) {
      statusEl.className = 'status status--error';
      statusEl.textContent = error || 'Submission failed. Please try again.';
      btn.disabled = false;
      return;
    }
    $('rqReview').hidden = true;
    $('rqWizard').hidden = true;
    $('rqThankYou').hidden = false;
    window.scrollTo({ top: 0, behavior: 'smooth' });
  } catch (err) {
    statusEl.className = 'status status--error';
    statusEl.textContent = 'Network error. Please try again.';
    btn.disabled = false;
  }
}

/* ---------- Invite a client (owner) ---------- */
async function showInviteModal() {
  const session = currentSession !== undefined ? currentSession : await getSession();
  if (!session) { showAuthModal(); return; }
  const base = `${window.location.origin}${window.location.pathname}`;
  $('inviteUrl').value = `${base}?for=${session.user.id}`;
  $('inviteModal').classList.add('modal--visible');
  $('inviteUrl').select();
}
function hideInviteModal() {
  $('inviteModal').classList.remove('modal--visible');
}

/* ---------- Share URL ---------- */
function buildShareUrl() {
  try {
    const encoded = btoa(unescape(encodeURIComponent(JSON.stringify(answers))));
    return `${window.location.origin}${window.location.pathname}#share=${encoded}`;
  } catch {
    return window.location.href;
  }
}

function restoreFromShare(hash) {
  try {
    const match = hash.match(/[#&]share=([^&]*)/);
    if (!match) return false;
    const decoded = JSON.parse(decodeURIComponent(escape(atob(match[1]))));
    if (decoded && typeof decoded === 'object') {
      answers = decoded;
      return true;
    }
  } catch { /* ignore */ }
  return false;
}

/* ---------- Auth ---------- */
let authMode = 'login';

function showAuthModal() {
  $('authModal').classList.add('modal--visible');
  $('authEmail').focus();
}
function hideAuthModal() {
  $('authModal').classList.remove('modal--visible');
}
function setAuthMode(mode) {
  authMode = mode;
  const isLogin = mode === 'login';
  $('authTitle').textContent = isLogin ? 'Sign in to PocketDevs' : 'Create an account';
  $('authSubmit').textContent = isLogin ? 'Sign in' : 'Create account';
  $('authNameRow').hidden = isLogin;
  $('authTabLogin').classList.toggle('btn--primary', isLogin);
  $('authTabLogin').classList.toggle('btn--ghost', !isLogin);
  $('authTabLogin').setAttribute('aria-pressed', String(isLogin));
  $('authTabSignup').classList.toggle('btn--primary', !isLogin);
  $('authTabSignup').classList.toggle('btn--ghost', isLogin);
  $('authTabSignup').setAttribute('aria-pressed', String(!isLogin));
}

async function handleAuth(e) {
  e.preventDefault();
  const email = $('authEmail').value.trim();
  const password = $('authPassword').value;
  const name = $('authName').value.trim();
  const errEl = $('authError');
  errEl.hidden = true;
  $('authSubmit').disabled = true;
  try {
    const { data, error } = authMode === 'login'
      ? await signIn(email, password)
      : await signUp(email, password, name);
    if (error) {
      errEl.textContent = error.message || String(error);
      errEl.className = 'status status--error';
      errEl.hidden = false;
    } else {
      hideAuthModal();
      updateAuthState(data?.session);
    }
  } catch (err) {
    errEl.textContent = 'Something went wrong. Please try again.';
    errEl.className = 'status status--error';
    errEl.hidden = false;
  } finally {
    $('authSubmit').disabled = false;
  }
}

async function updateAuthState(session) {
  if (session === undefined) session = await getSession();
  currentSession = session;
  const isLoggedIn = !!session;
  $('rqAuthBtn').hidden = isLoggedIn;
  $('rqAuthGreeting').hidden = !isLoggedIn;
  $('rqInviteBtn').hidden = !isLoggedIn || !!clientInviteOwnerId;
  if (isLoggedIn) {
    const name = session.user.user_metadata?.full_name || session.user.email || '';
    $('rqAuthGreeting').textContent = `Hi, ${name.split(' ')[0] || name}`;
  }
}

/* ---------- Status helper ---------- */
function setStatus(kind, html) {
  const el = $('rqStatus');
  el.className = `status${kind ? ' status--' + kind : ''}`;
  el.innerHTML = html;
  el.hidden = false;
}

/* ---------- Generate SRD ---------- */
async function generateSRD() {
  const session = currentSession !== undefined ? currentSession : await getSession();
  if (!session || !session.access_token) {
    showAuthModal();
    setStatus('error', 'Please sign in to generate the SRD.');
    return;
  }

  const btn = $('rqGenerateBtn');
  btn.disabled = true;
  setStatus('working', '<span class="spinner"></span> Reading your answers and drafting the System Requirements Document… this can take 30–60 seconds.');

  try {
    const res = await fetch(REQ_API_URL, {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        'apikey': SUPABASE_ANON_KEY,
        'authorization': `Bearer ${session.access_token}`,
      },
      body: JSON.stringify({ answers }),
    });
    const data = await res.json();
    if (!res.ok) {
      if (res.status === 401) showAuthModal();
      setStatus('error', `Generation failed: ${esc(data?.error?.message || `HTTP ${res.status}`)}`);
      return;
    }
    const srd = data.srd;
    if (!srd) { setStatus('error', 'No SRD returned. Please try again.'); return; }
    renderSRD(srd);
    $('rqStatus').hidden = true;
    // Best-effort save to DB
    const docNo = `SRD-${new Date().getFullYear()}${String(new Date().getMonth() + 1).padStart(2, '0')}${String(new Date().getDate()).padStart(2, '0')}`;
    const submissionData = {
      ...(currentSubmissionId ? { id: currentSubmissionId } : {}),
      client_name: answers.contactCompany || answers.contactName || '',
      project_name: answers.projectName || srd.projectName || '',
      project_type: answers.projectType || '',
      answers,
      srd_content: srd,
      doc_number: docNo,
      status: 'srd_generated',
    };
    try {
      const { data: saved, error } = await saveQuestionnaire(submissionData);
      if (!error && saved && saved[0]) currentSubmissionId = saved[0].id;
    } catch { /* non-blocking */ }
  } catch (err) {
    setStatus('error', `Network error: ${esc(err.message)}`);
  } finally {
    btn.disabled = false;
  }
}

/* ---------- Render SRD ---------- */
function renderSRD(srd) {
  const clientName = answers.contactName || '';
  const clientCompany = answers.contactCompany || '';
  const now = new Date().toLocaleDateString('en-PH', { year: 'numeric', month: 'long', day: 'numeric' });
  const docNo = `SRD-${new Date().getFullYear()}${String(new Date().getMonth() + 1).padStart(2, '0')}${String(new Date().getDate()).padStart(2, '0')}`;
  const projectType = { website: 'Website', webapp: 'Web Application', mobile: 'Mobile Application', software: 'Custom Software' }[answers.projectType] || answers.projectType || '';

  const cover = `
    <header class="p-cover">
      <div class="p-cover__top">
        <img src="assets/logo.svg" alt="Logo" class="p-cover__logo js-logo" />
        <div class="p-eyebrow">
          <div class="js-doc-no"><b>${esc(docNo)}</b></div>
          <div>Prepared ${esc(now)}</div>
          <div>${esc(projectType)}</div>
        </div>
      </div>
      <span class="p-kicker">System Requirements Document</span>
      <h1 class="p-title">${esc(srd.projectName || answers.projectName || 'Project SRD')}</h1>
      <div class="p-parties">
        <div class="p-party">
          <div class="p-party__label">Prepared for</div>
          <div class="p-party__name">${esc(clientCompany || clientName || '[Client]')}</div>
          ${clientName && clientCompany ? `<div class="p-party__meta">${esc(clientName)}</div>` : ''}
        </div>
        <div class="p-party">
          <div class="p-party__label">Prepared by</div>
          <div class="p-party__name">PocketDevs</div>
          <div class="p-party__meta">www.pocketdevs.ph</div>
        </div>
      </div>
    </header>`;

  const sec = [];

  /* 1. Introduction */
  const defsHtml = terms(srd.definitions, 'term', 'definition');
  sec.push(`<section class="p-section">
    ${sectionHead(1, 'Introduction')}
    ${subHead(1, 1, 'Purpose')}<div class="p-lede"><p>${esc(srd.purpose || '')}</p></div>
    ${subHead(1, 2, 'Scope')}<div class="p-lede"><p>${esc(srd.scope || '')}</p></div>
    ${subHead(1, 3, 'Definitions and Acronyms')}${defsHtml}
    ${subHead(1, 4, 'References')}${list(SRD_REFERENCES)}
    ${subHead(1, 5, 'Overview')}<div class="p-lede"><p>${esc(SRD_OVERVIEW)}</p></div>
  </section>`);

  /* 2. Overall Description */
  const userClassRows = (srd.userClasses || []).map((u) =>
    `<tr><td><strong>${esc(u.name)}</strong></td><td>${esc(u.description)}</td><td>${esc(u.technicalSkill)}</td></tr>`
  ).join('');
  const envHtml = terms(srd.operatingEnvironment, 'label', 'value');
  sec.push(`<section class="p-section">
    ${sectionHead(2, 'Overall Description')}
    ${subHead(2, 1, 'Product Perspective')}<div class="p-lede"><p>${esc(srd.productPerspective || '')}</p></div>
    ${subHead(2, 2, 'Product Functions')}${list(srd.productFunctions)}
    ${subHead(2, 3, 'User Classes and Characteristics')}
    <table class="p-table"><thead><tr><th>User Class</th><th>Description</th><th>Technical Skill</th></tr></thead><tbody>${userClassRows}</tbody></table>
    ${subHead(2, 4, 'Operating Environment')}${envHtml}
    ${subHead(2, 5, 'Design and Implementation Constraints')}${list(srd.designConstraints)}
    ${subHead(2, 6, 'Assumptions and Dependencies')}${list(srd.assumptionsAndDependencies)}
  </section>`);

  /* 3. Functional Requirements */
  let frCounter = 1;
  const frHtml = (srd.functionalRequirements || []).map((mod, i) => {
    const reqsHtml = (mod.requirements || []).map((r) => {
      const id = `FR-${frCounter++}`;
      const prio = (r.priority || '').toLowerCase();
      return `<li><span class="p-req__id">${esc(id)}</span>${esc(r.text)}<span class="p-req__tag p-req__tag--${esc(prio)}">${esc(r.priority || '')}</span></li>`;
    }).join('');
    return `${subHead(3, i + 1, mod.module)}<ul class="p-list p-req-list">${reqsHtml}</ul>`;
  }).join('');
  sec.push(`<section class="p-section">
    ${sectionHead(3, 'Functional Requirements')}
    <p class="p-section__intro">Each requirement below is identified by a unique ID (FR-x) and tagged with a priority: <b>Must</b> (mandatory for launch), <b>Should</b> (important but not launch-blocking), or <b>Could</b> (desirable if time and budget allow).</p>
    ${frHtml}
  </section>`);

  /* 4. External Interface Requirements */
  const swIfaceHtml = terms(srd.softwareInterfaces, 'name', 'description');
  sec.push(`<section class="p-section">
    ${sectionHead(4, 'External Interface Requirements')}
    ${subHead(4, 1, 'User Interfaces')}${list(srd.userInterfaces)}
    ${subHead(4, 2, 'Hardware Interfaces')}<div class="p-lede"><p>${esc(srd.hardwareInterfaces || 'No special hardware interfaces are required.')}</p></div>
    ${subHead(4, 3, 'Software Interfaces')}${swIfaceHtml}
    ${subHead(4, 4, 'Communication Interfaces')}${list(srd.communicationInterfaces)}
  </section>`);

  /* 5. Non-Functional Requirements */
  let nfrCounter = 1;
  const nfrHtml = (srd.nonFunctionalRequirements || []).map((cat, i) => {
    const reqsHtml = (cat.requirements || []).map((r) => {
      const id = `NFR-${nfrCounter++}`;
      return `<li><span class="p-req__id">${esc(id)}</span>${esc(r)}</li>`;
    }).join('');
    return `${subHead(5, i + 1, cat.category)}<ul class="p-list p-req-list">${reqsHtml}</ul>`;
  }).join('');
  sec.push(`<section class="p-section">${sectionHead(5, 'Non-Functional Requirements')}${nfrHtml}</section>`);

  /* 6. Other Requirements */
  sec.push(`<section class="p-section">
    ${sectionHead(6, 'Other Requirements')}
    ${subHead(6, 1, 'Data Requirements')}${list(srd.dataRequirements)}
    ${subHead(6, 2, 'Legal and Compliance')}${list(srd.legalAndCompliance)}
    ${subHead(6, 3, 'Acceptance Criteria')}${list(srd.acceptanceCriteria)}
  </section>`);

  /* Appendix A — Requirement Priority Legend (static) */
  sec.push(`<section class="p-section">
    <div class="p-section__head"><span class="p-section__num">A</span><h2 class="p-section__title">Appendix A — Requirement Priority Legend</h2></div>
    <ul class="p-list">
      <li><b>Must</b> — Mandatory. The system will not be considered complete without this requirement.</li>
      <li><b>Should</b> — Important, but the system can launch without it if necessary.</li>
      <li><b>Could</b> — Desirable. Implemented only if time and budget allow.</li>
    </ul>
  </section>`);

  /* Appendix B — Revision History (static, dated) */
  sec.push(`<section class="p-section">
    <div class="p-section__head"><span class="p-section__num">B</span><h2 class="p-section__title">Appendix B — Revision History</h2></div>
    <table class="p-table"><thead><tr><th>Version</th><th>Date</th><th>Author</th><th>Notes</th></tr></thead>
    <tbody><tr><td>1.0</td><td>${esc(now)}</td><td>PocketDevs</td><td>Initial draft generated from the client intake questionnaire</td></tr></tbody></table>
  </section>`);

  const footer = `<div class="p-docfooter"><span><b>PocketDevs</b></span><span>Confidential</span><span>www.pocketdevs.ph</span></div>`;

  const art = $('rqSRD');
  art.innerHTML = cover + sec.join('') + footer;
  art.setAttribute('contenteditable', 'true');
  art.setAttribute('spellcheck', 'false');

  $('rqSRDSection').hidden = false;
  $('rqEditorToolbar').hidden = false;
  $('rqDownloadBtn').hidden = false;

  window.scrollTo({ top: 0, behavior: 'smooth' });
}

/* ---------- PDF Download ---------- */
function downloadPDF() {
  const element = $('rqSRD');
  const docNo = document.querySelector('#rqSRD .js-doc-no')?.innerText?.trim() || 'SRD';
  const opt = {
    margin: [15, 15],
    filename: `${docNo}.pdf`,
    image: { type: 'jpeg', quality: 0.98 },
    html2canvas: { scale: 2, useCORS: true, letterRendering: true, scrollX: 0, scrollY: -window.scrollY, windowWidth: document.documentElement.scrollWidth },
    jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
    pagebreak: { mode: ['avoid-all', 'css', 'legacy'] },
  };
  html2pdf().set(opt).from(element).save();
}

/* ---------- Rich text toolbar ---------- */
(function initToolbar() {
  document.addEventListener('DOMContentLoaded', () => {
    const toolbar = $('rqEditorToolbar');
    if (!toolbar) return;
    toolbar.querySelectorAll('[data-cmd]').forEach((btn) => {
      btn.addEventListener('mousedown', (e) => {
        e.preventDefault();
        document.execCommand(btn.dataset.cmd, false, null);
      });
    });
  });
})();

/* ---------- Init ---------- */
async function init() {
  const urlParams = new URLSearchParams(window.location.search);

  // Check for ?for=<ownerId> (a client filling the questionnaire via invite link)
  const inviteOwnerId = urlParams.get('for');
  if (inviteOwnerId) {
    clientInviteOwnerId = inviteOwnerId;
    document.body.classList.add('client-intake');
    renderCurrentQuestion();
    setupWiring();
    return;
  }

  // Check for ?submission=ID (from dashboard link)
  const submissionId = urlParams.get('submission');
  if (submissionId) {
    await updateAuthState();
    const submission = await fetchSubmissionById(submissionId);
    if (submission) {
      currentSubmissionId = submission.id;
      answers = submission.answers || {};
      isShareMode = true;
      showReview();
      if (submission.srd_content) {
        renderSRD(submission.srd_content);
      }
      // Clean up URL param without page reload
      const url = new URL(window.location.href);
      url.searchParams.delete('submission');
      window.history.replaceState({}, '', url.toString());
    } else {
      renderCurrentQuestion();
    }
    // Skip the rest of init's auth call since we already did it
    setupWiring();
    return;
  }

  const hash = window.location.hash;
  if (hash && hash.includes('share=')) {
    if (restoreFromShare(hash)) {
      isShareMode = true;
      showReview();
    } else {
      renderCurrentQuestion();
    }
  } else {
    renderCurrentQuestion();
  }

  setupWiring();
}

function setupWiring() {
  const clientMode = !!clientInviteOwnerId;
  if (!clientMode) initLayout({ activePage: 'requirements' });

  $('rqNextBtn').addEventListener('click', goNext);
  $('rqBackBtn').addEventListener('click', goBack);
  $('rqEditBtn').addEventListener('click', showWizard);
  $('rqSubmitBtn').addEventListener('click', submitClientAnswers);

  $('rqCopyBtn').addEventListener('click', () => {
    const url = $('rqShareUrl').value;
    navigator.clipboard?.writeText(url).then(() => {
      $('rqCopyBtn').textContent = 'Copied!';
      setTimeout(() => { $('rqCopyBtn').textContent = 'Copy link'; }, 2000);
    });
  });

  // Invite-a-client modal (owner)
  $('rqInviteBtn').addEventListener('click', showInviteModal);
  $('closeInvite').addEventListener('click', hideInviteModal);
  $('inviteModal').addEventListener('click', (e) => { if (e.target === $('inviteModal')) hideInviteModal(); });
  $('inviteCopyBtn').addEventListener('click', () => {
    navigator.clipboard?.writeText($('inviteUrl').value).then(() => {
      $('inviteCopyBtn').textContent = 'Copied!';
      setTimeout(() => { $('inviteCopyBtn').textContent = 'Copy'; }, 2000);
    });
  });

  $('rqGenerateBtn').addEventListener('click', generateSRD);
  $('rqDownloadBtn').addEventListener('click', downloadPDF);

  $('rqAuthBtn').addEventListener('click', showAuthModal);
  $('closeAuth').addEventListener('click', hideAuthModal);
  $('authModal').addEventListener('click', (e) => { if (e.target === $('authModal')) hideAuthModal(); });
  $('authTabLogin').addEventListener('click', () => setAuthMode('login'));
  $('authTabSignup').addEventListener('click', () => setAuthMode('signup'));
  $('authForm').addEventListener('submit', handleAuth);

  // Keyboard navigation (Typeform-style)
  document.addEventListener('keydown', (e) => {
    // Never intercept keyboard events when a modal is open
    if ($('authModal').classList.contains('modal--visible')) return;
    if ($('inviteModal').classList.contains('modal--visible')) return;
    if ($('rqWizard').hidden) return;
    const tag = e.target.tagName;
    const typing = tag === 'INPUT' || tag === 'TEXTAREA';

    // Letter keys (A, B, C…) select a choice when not typing in a field
    if (!typing && !e.metaKey && !e.ctrlKey && !e.altKey && /^[a-zA-Z]$/.test(e.key)) {
      const wrap = $('rqStepCard').querySelector('.tf-choices');
      if (wrap) {
        const idx = e.key.toUpperCase().charCodeAt(0) - 65;
        const btns = wrap.querySelectorAll('.tf-choice');
        if (idx >= 0 && idx < btns.length) {
          e.preventDefault();
          selectChoice(btns[idx], wrap.dataset.multi === 'true');
          return;
        }
      }
    }

    // Enter advances (but allow newlines inside a textarea)
    if (e.key === 'Enter' && tag !== 'TEXTAREA') {
      e.preventDefault();
      goNext();
    }
  });

  // Clients filling via an invite link don't need any account UI.
  if (clientMode) return;

  // Optimistically hide the Login button if there's a stored session,
  // so the user doesn't see a flash while Supabase initializes.
  try {
    const hasStored = Object.keys(localStorage).some((k) => k.includes('-auth-token'));
    if (hasStored) $('rqAuthBtn').hidden = true;
  } catch { /* ignore */ }

  onAuthChange((session) => updateAuthState(session));
}

init();
